IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='tblCheckGroup') BEGIN
	CREATE TABLE dbo.tblCheckGroup (
		ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
		Name VARCHAR(255) NOT NULL
	)
END