IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='tblCheckNotificationTypeOption' AND COLUMN_NAME='Multiple') BEGIN
	ALTER TABLE dbo.tblCheckNotificationTypeOption ADD Multiple BIT NOT NULL CONSTRAINT DEFAULT_TEMP DEFAULT 0
	ALTER TABLE dbo.tblCheckNotificationTypeOption DROP CONSTRAINT DEFAULT_TEMP
END