sudo: required
language: csharp
mono: none
cache: yarn
dotnet: 2.0.3
if: tag IS blank

services:
  - docker
  
before_script:
  - export major=$(cat meta.json | jq '.version.major')
  - export minor=$(cat meta.json | jq '.version.minor')
  - export patch=$(cat meta.json | jq '.version.patch')
  - export version=$major.$minor.$patch

script:
  - docker build -t mattjeanes/systemchecker.service -t mattjeanes/systemchecker.service:$version -f "SystemChecker.Service/Dockerfile" .
  - docker build -t mattjeanes/systemchecker.web -t mattjeanes/systemchecker.web:$version -f "SystemChecker.Web/Dockerfile" .
  - docker build -t mattjeanes/systemchecker.migrations -t mattjeanes/systemchecker.migrations:$version -f "SystemChecker.Migrations/Dockerfile" "SystemChecker.Migrations"
  - dotnet publish ./SystemChecker.Service/SystemChecker.Service.csproj -o "../publish/SystemChecker.Service" --configfile ../.nuget/nuget.config
  - yarn --cwd SystemChecker.Web
  - dotnet publish ./SystemChecker.Web/SystemChecker.Web.csproj -o "../publish/SystemChecker.Web" --configfile ../.nuget/nuget.config
  - dotnet publish ./SystemChecker.Migrations/SystemChecker.Migrations.csproj -o "../publish/SystemChecker.Migrations"
  
after_success:
  - git config --local user.name "$GITHUB_USER"
  - git config --local user.email "$GITHUB_EMAIL"
  - if ! git rev-parse "$version" >/dev/null 2>&1; then git tag "$version"; TRAVIS_TAG="$version"; fi

before_deploy:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push mattjeanes/systemchecker.service:$version
  - docker push mattjeanes/systemchecker.service
  - docker push mattjeanes/systemchecker.web:$version
  - docker push mattjeanes/systemchecker.web
  - docker push mattjeanes/systemchecker.migrations:$version
  - docker push mattjeanes/systemchecker.migrations
  - zip -q -r SystemChecker.Service.zip SystemChecker.Service
  - zip -q -r SystemChecker.Web.zip SystemChecker.Web
  - zip -q -r SystemChecker.Migrations.zip SystemChecker.Migrations
deploy:
  provider: releases
  api_key: "${GITHUB_TOKEN}"
  file_glob: true
  file: publish/*.zip
  skip_cleanup: true
  on:
    all_branches: true
    tags: true