CREATE TABLE dbo.tblUser (
	[ID] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Username] VARCHAR(255) NOT NULL,
	[Password] VARCHAR(MAX) NULL,
	[IsWindowsUser] BIT NOT NULL
)

CREATE TABLE dbo.tblApiKey(
	[ID] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[UserID] INT NOT NULL,
	[Name] VARCHAR(255),
	[Key] VARCHAR(255),
	FOREIGN KEY (UserID) REFERENCES dbo.tblUser
)