IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='tblCheck' AND COLUMN_NAME='EnvironmentID') BEGIN
	ALTER TABLE dbo.tblCheck ADD EnvironmentID INT NOT NULL CONSTRAINT Default_tblCheck_TEMP DEFAULT 1
	ALTER TABLE dbo.tblCheck DROP CONSTRAINT Default_tblCheck_TEMP
END